baseurl = "https://praneelrathore.github.io/"
languageCode = "en-us"
title = "Praneel Rathore"
theme = "introduction"
copyright = ""
publishdir = "praneelrathore.github.io"
[params]
	Author = "Praneel Rathore"
	description = "Hide-n-seek"
	gravatar = "/Users/zomato/Code/personal/hide-n-seek/static/IMG_3829.png"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
