baseurl = ""
languageCode = "en-us"
title = "Praneel Rathore"
theme = "soho"
copyright = ""
publishdir = "praneelrathore.github.io"
[Author]
	name = "Praneel Rathore"
[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"
[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"
[params]
	Author = "Praneel Rathore"
	description = "My Blog - Hide-n-seek"
	twitter = "https://twitter.com/praneelrathore"
	github = "https://github.com/praneelrathore"
	disqus = ""
