baseURL = "https://praneelrathore.github.io/"
title = "Praneel Rathore"
theme = "introduction"
copyright = ""
publishdir = "praneelrathore.github.io"
[params]
	Author = "Praneel Rathore"
	description = "Hide-n-seek"
	dateFormat = "Jan 2, 2006"
	email = "praneelrathore@gmail.com"

	[[params.social]]
        url   = "https://twitter.com/praneelrathore"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/praneel-rathore-66215bba/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:praneelrathore@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"
	[[params.social]]
        url   = "https://www.github.com/praneelrathore"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"